version: '3.8'

services:
  product-search:
    build: 
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    image: antrinh/product-search:lts
    container_name: product-search
    user: root
    ports:
      - "8001:8001"
    env_file:
      - .env
