image:
  repository: antrinh/product-search
  tag: 0.1.12
  pullPolicy: Always

replicas: 1

openai_api_key: openai_api_key
pinecone_api_key: pinecone_api_key

jaeger:
  agent_host: jaeger.monitoring.svc.cluster.local
  agent_port: 6831
