apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
  namespace: product-search
spec:
  selector:
    app: {{ .Release.Name }}
  ports:
    - port: 8001
      protocol: TCP
      targetPort: 8001
  type: NodePort
