# embedding_model: BAAI/bge-small-en-v1.5
# device: cuda
# normalize_embeddings: True
# db_path: databases/embeddings

vector_store_config:
  embedding_model: text-embedding-3-small
  embedding_dim: 256
  pinecone_index_name: product-search-embeddings
